apiVersion: v1
kind: Service
metadata:
  name: cs3219-db
  namespace: cs3219
spec:
  type: ClusterIP # ClusterIP
  selector:
    app: cs3219-db
  ports:
    - port: 3306
      targetPort: 3306
# kubectl apply -f "./kubernetes/02 - mariadb-service.yaml"