apiVersion: v1
kind: Service
metadata:
  name: cs3219-db
spec:
  type: NodePort
  selector:
    app: cs3219-db
  ports:
    - port: 3306
      targetPort: 3306
# kubectl apply --namespace=cs3219 -f "./kubernetes/02 - mariadb-service.yaml"