apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cs3219
  labels:
    app: order-service
spec:
  type: ClusterIP # ClusterIP
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# kubectl apply -f "./kubernetes/08 - order-service.yaml"