apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cs3219
  labels:
    app: api-gateway
spec:
  type: LoadBalancer 
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
# kubectl apply -f "./kubernetes/10 - api-gateway-service.yaml"
